--------------------------------------------------------
--  DDL for Table PROMOTION_HISTORY
--------------------------------------------------------

  CREATE TABLE "SILKERP"."PROMOTION_HISTORY" 
   (	"PROMOTION_ID" NUMBER(20,0), 
	"EMPLOYEE_CODE" NUMBER(20,0), 
	"PREVIOUS_DESIGNATION_CODE" NUMBER(20,0), 
	"CURRENT_DESIGNATION_CODE" NUMBER(20,0), 
	"EFFECTIVE_FROM" DATE, 
	"REMARKS" VARCHAR2(500 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"COMPANY_CODE" NUMBER(12,0), 
	"ISAPPROVED" NUMBER(*,0), 
	"INCREMENT_CODE" NUMBER(16,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROMOTION_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SILKERP"."PROMOTION_HISTORY_PK" ON "SILKERP"."PROMOTION_HISTORY" ("PROMOTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROMOTION_HISTORY
--------------------------------------------------------

  ALTER TABLE "SILKERP"."PROMOTION_HISTORY" MODIFY ("PROMOTION_ID" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."PROMOTION_HISTORY" MODIFY ("EMPLOYEE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."PROMOTION_HISTORY" MODIFY ("PREVIOUS_DESIGNATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."PROMOTION_HISTORY" MODIFY ("CURRENT_DESIGNATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."PROMOTION_HISTORY" MODIFY ("EFFECTIVE_FROM" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."PROMOTION_HISTORY" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."PROMOTION_HISTORY" ADD CONSTRAINT "PROMOTION_HISTORY_PK" PRIMARY KEY ("PROMOTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SILKERP"."PROMOTION_HISTORY" MODIFY ("COMPANY_CODE" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."PROMOTION_HISTORY" MODIFY ("ISAPPROVED" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PROMOTION_HISTORY
--------------------------------------------------------

  ALTER TABLE "SILKERP"."PROMOTION_HISTORY" ADD CONSTRAINT "PROMOTION_HISTORY_FK1" FOREIGN KEY ("INCREMENT_CODE")
	  REFERENCES "SILKERP"."SALARY_INCREMENT" ("INCREMENT_CODE") ENABLE;
  ALTER TABLE "SILKERP"."PROMOTION_HISTORY" ADD CONSTRAINT "PROMOTION_HISTORY_FK2" FOREIGN KEY ("PREVIOUS_DESIGNATION_CODE")
	  REFERENCES "SILKERP"."DESIGNATION" ("DESIGNATION_CODE") ENABLE;
  ALTER TABLE "SILKERP"."PROMOTION_HISTORY" ADD CONSTRAINT "PROMOTION_HISTORY_FK3" FOREIGN KEY ("CURRENT_DESIGNATION_CODE")
	  REFERENCES "SILKERP"."DESIGNATION" ("DESIGNATION_CODE") ENABLE;
  ALTER TABLE "SILKERP"."PROMOTION_HISTORY" ADD CONSTRAINT "PROMOTION_HISTORY_FK4" FOREIGN KEY ("COMPANY_CODE")
	  REFERENCES "SILKERP"."COMPANY" ("COMPANY_CODE") ENABLE;







--------------------------------------------------------
--  DDL for Table PROMOTION_APPROVERS
--------------------------------------------------------

  CREATE TABLE "SILKERP"."PROMOTION_APPROVERS" 
   (	"ID" NUMBER(12,0), 
	"HISTORY_ID" NUMBER(20,0), 
	"EMPLOYEE_CODE" NUMBER(20,0), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROMOTION_APPROVERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SILKERP"."PROMOTION_APPROVERS_PK" ON "SILKERP"."PROMOTION_APPROVERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROMOTION_APPROVERS
--------------------------------------------------------

  ALTER TABLE "SILKERP"."PROMOTION_APPROVERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."PROMOTION_APPROVERS" MODIFY ("HISTORY_ID" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."PROMOTION_APPROVERS" MODIFY ("EMPLOYEE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."PROMOTION_APPROVERS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."PROMOTION_APPROVERS" ADD CONSTRAINT "PROMOTION_APPROVERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROMOTION_APPROVERS
--------------------------------------------------------

  ALTER TABLE "SILKERP"."PROMOTION_APPROVERS" ADD CONSTRAINT "PROMOTION_APPROVERS_FK1" FOREIGN KEY ("HISTORY_ID")
	  REFERENCES "SILKERP"."PROMOTION_HISTORY" ("PROMOTION_ID") ENABLE;



--------------------------------------------------------
--  DDL for Sequence SEQ_PROMOTION_APPROVERS
--------------------------------------------------------

   CREATE SEQUENCE  "SILKERP"."SEQ_PROMOTION_APPROVERS"  MINVALUE 10001 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10005 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;





--------------------------------------------------------
--  DDL for Table TOKENS
--------------------------------------------------------

  CREATE TABLE "SILKERP"."TOKENS" 
   (	"TOKEN_ID" VARCHAR2(50 BYTE), 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"IS_VALID" NUMBER(1,0) DEFAULT 1, 
	"EXPIRY_AT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TOKENS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SILKERP"."TOKENS_PK" ON "SILKERP"."TOKENS" ("TOKEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TOKENS
--------------------------------------------------------

  ALTER TABLE "SILKERP"."TOKENS" MODIFY ("TOKEN_ID" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."TOKENS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."TOKENS" MODIFY ("IS_VALID" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."TOKENS" MODIFY ("EXPIRY_AT" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."TOKENS" ADD CONSTRAINT "TOKENS_PK" PRIMARY KEY ("TOKEN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;




  --------------------------------------------------------
--  DDL for Table "SALARY_INCREMENT_REQUEST"
--------------------------------------------------------

  CREATE TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" 
   ("INCREMENT_CODE" NUMBER(16,0), 
	"EMPLOYEE_CODE" NUMBER(16,0), 
	"INCREMENT_DATE" DATE DEFAULT SYSDATE, 
	"PREVIOUS_GROSS" NUMBER, 
	"INC_BASIC" NUMBER DEFAULT 0, 
	"INC_HOURSE_RENT" NUMBER, 
	"INC_CONVEYENCE" NUMBER DEFAULT 0, 
	"INC_MEDICAL" NUMBER DEFAULT 0, 
	"INC_ENTERTAINMENT" NUMBER DEFAULT 0, 
	"INC_GROSS" NUMBER DEFAULT 0, 
	"ENTRY_DATE" DATE DEFAULT SYSDATE, 
	"ENTRY_EMPLOYEE_CODE" NUMBER, 
	"EFFECTIVE_MONTH" NUMBER DEFAULT 7, 
	"EFFECTIVE_YEAR" NUMBER DEFAULT 2015,
    "IS_APPROVED" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index "SALARY_INCREMENT_REQUEST_PK"
--------------------------------------------------------

  CREATE UNIQUE INDEX "SILKERP"."SALARY_INCREMENT_REQUEST_PK" ON "SILKERP"."SALARY_INCREMENT_REQUEST" ("INCREMENT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table "SALARY_INCREMENT_REQUEST"
--------------------------------------------------------

  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("INCREMENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("EMPLOYEE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("INCREMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("PREVIOUS_GROSS" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("INC_BASIC" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("INC_HOURSE_RENT" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("INC_CONVEYENCE" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("INC_MEDICAL" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("INC_ENTERTAINMENT" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("INC_GROSS" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("ENTRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("ENTRY_EMPLOYEE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("EFFECTIVE_MONTH" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("EFFECTIVE_YEAR" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" MODIFY ("IS_APPROVED" NOT NULL ENABLE);
  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" ADD CONSTRAINT "SALARY_INCREMENT_REQUEST_PK" PRIMARY KEY ("INCREMENT_CODE")
  USING INDEX "SILKERP"."SALARY_INCREMENT_REQUEST_PK"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALARY_INCREMENT
--------------------------------------------------------

  ALTER TABLE "SILKERP"."SALARY_INCREMENT_REQUEST" ADD CONSTRAINT "SALARY_INCREMENT_REQUEST_EMPLOYEE_FK1" FOREIGN KEY ("EMPLOYEE_CODE")
	  REFERENCES "SILKERP"."EMPLOYEE" ("EMPLOYEE_CODE") ENABLE;





--------------------------------------------------------
--  DDL for Sequence SEQ_REQUEST_INCREMENT
--------------------------------------------------------

   CREATE SEQUENCE  "SILKERP"."SEQ_REQUEST_INCREMENT"  MINVALUE 501000000000001 MAXVALUE 501999999999999 INCREMENT BY 1 START WITH 501000000000001 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;




